use_frameworks!

platform :ios, '9.0'

target 'QTLMediator_Example' do
  pod 'QTLMediator', :path => '../'

  target 'QTLMediator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
